### ISSUE TITLE
Uncaught TypeError: Cannot read property 'unit_system' of undefined

### ISSUE THREAD

**Issue by acharest** [iammexx/home-assistant-config#1]
Hi,

I get this error in Lovelace:
Uncaught TypeError: Cannot read property 'unit_system' of undefined
07:34 components/system_log/__init__.py (ERROR)

I think my units are not defined properly

**Comment by KuruKanagalingam** [comment]
I am seeing this too I followed the steps from here

https://unpkg.com/@polymer/polymer@3.1.0/lib/utils/async.js?module:44:11 Uncaught TypeError: Cannot read property 'attributes' of undefined.

It works mine was due to poor format of the ui-lovelace statements. Correct one that works as bellow
""
  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
    cards:
      - id: dark_sky_animated_card
        type: custom:dark-sky-weather-card
""

**Comment by IIIdefconIII** [comment]
getting the same errors tried several formattings, using 0.84

**Comment by iammexx** [comment]
Please post card configuration and dark sky configuration

**Comment by IIIdefconIII** [comment]
YAML FILE
```
############################################
##                WEATHER                 ##
############################################
###### SENSORS -----------------------------
sensor:
  - platform: darksky
    api_key: xxx
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    update_interval:
      minutes: 5
```

Card content on 0.84 configure UI:
```
entity_current_conditions: sensor.dark_sky_icon
entity_daily_summary: sensor.dark_sky_daily_summary
entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2
entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3
entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4
entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5
entity_forecast_icon_1: sensor.dark_sky_icon_1
entity_forecast_icon_2: sensor.dark_sky_icon_2
entity_forecast_icon_3: sensor.dark_sky_icon_3
entity_forecast_icon_4: sensor.dark_sky_icon_4
entity_forecast_icon_5: sensor.dark_sky_icon_5
entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_0
entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1
entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2
entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3
entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4
entity_humidity: sensor.dark_sky_humidity
entity_pressure: sensor.dark_sky_pressure
entity_summary_1: sensor.dark_sky_summary_1
entity_summary_2: sensor.dark_sky_summary_2
entity_summary_3: sensor.dark_sky_summary_3
entity_summary_4: sensor.dark_sky_summary_4
entity_summary_5: sensor.dark_sky_summary_5
entity_sun: sun.sun
entity_temperature: sensor.dark_sky_temperature
entity_visibility: sensor.dark_sky_visibility
entity_wind_bearing: sensor.dark_sky_wind_bearing
entity_wind_speed: sensor.dark_sky_wind_speed
locale: en
static_icons: false
sunset: true
tooltip_bg_color: 'rgb( 75,155,239)'
tooltip_border_color: orange
tooltip_border_width: 3
tooltip_caret_size: 10
tooltip_fg_color: '#fff'
tooltip_left_offset: -5
tooltip_width: 100
tooltips: true
type: 'custom:dark-sky-weather-card'
```

RAW EDIT:
while this works with default weather card:
```
     - cards:
          - entity: weather.dark_sky
            type: weather-forecast
          - aspect_ratio: 100%
            entity: null
            type: iframe
            url: 'https://embed.windy.com/embed2.html'
```

RAW EDIT:
and this gives the error:
```
 - badges: []
    cards:
      - entities:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
        title: Tracker Card
        trackers: null
        type: entities
      - entity_current_conditions: sensor.dark_sky_icon
        entity_daily_summary: sensor.dark_sky_daily_summary
        entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
        entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2
        entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3
        entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4
        entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5
        entity_forecast_icon_1: sensor.dark_sky_icon_1
        entity_forecast_icon_2: sensor.dark_sky_icon_2
        entity_forecast_icon_3: sensor.dark_sky_icon_3
        entity_forecast_icon_4: sensor.dark_sky_icon_4
        entity_forecast_icon_5: sensor.dark_sky_icon_5
        entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_0
        entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1
        entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2
        entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3
        entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4
        entity_humidity: sensor.dark_sky_humidity
        entity_pressure: sensor.dark_sky_pressure
        entity_summary_1: sensor.dark_sky_summary_1
        entity_summary_2: sensor.dark_sky_summary_2
        entity_summary_3: sensor.dark_sky_summary_3
        entity_summary_4: sensor.dark_sky_summary_4
        entity_summary_5: sensor.dark_sky_summary_5
        entity_sun: sun.sun
        entity_temperature: sensor.dark_sky_temperature
        entity_visibility: sensor.dark_sky_visibility
        entity_wind_bearing: sensor.dark_sky_wind_bearing
        entity_wind_speed: sensor.dark_sky_wind_speed
        locale: en
        static_icons: false
        sunset: true
        tooltip_bg_color: 'rgb( 75,155,239)'
        tooltip_border_color: orange
        tooltip_border_width: 3
        tooltip_caret_size: 10
        tooltip_fg_color: '#fff'
        tooltip_left_offset: -5
        tooltip_width: 100
        tooltips: true
        type: 'custom:dark-sky-weather-card'
    title: TEST
```
