### ISSUE TITLE
configuration error: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by aplsms** [iammexx/home-assistant-config#25]
Hello, 
i'm trying to add card to the my HA and have multiple errors.

```
Uncaught (in promise) TypeError: Cannot read property 'state' of undefined
    at HTMLElement.get current [as current] (dark-sky-weather-card.js?v=7.1:307)
    at HTMLElement.render (dark-sky-weather-card.js?v=7.1:33)
    at HTMLElement.value (app-badd6e6f.js:2)
    at HTMLElement.value (app-badd6e6f.js:2)
    at HTMLElement.<anonymous> (app-badd6e6f.js:2)
    at j (compatibility-e3292283.js:1)
    at Generator._invoke (compatibility-e3292283.js:1)
    at Generator.t.(anonymous function) [as next] (http://192.168.1.178:8123/frontend_es5/compatibility-e3292283.js:1:8262)
    at k (app-badd6e6f.js:2)
    at a (app-badd6e6f.js:2)
```

could you please correct me/my configuration related to dark-sky-weather-card

Thank you in advance,

My config:
```
resources:
  - url: /local/custom_ui/dark-sky-weather-card.js?v=7.1
    type: module
title: Home
views:
  - badges:
      - person.andrii_petrenko
      - sensor.yr_symbol
      - sun.sun
      - sensor.ds_home_hourly_summary
      - zone.home
    cards:
      - entities:
          - entity: sensor.date_time
          - entity: sensor.date_time_iso
          - entity: sensor.time_utc
        show_header_toggle: false
        title: Information
        type: entities
      - entity: weather.home
        name: Home
        type: weather-forecast
      - entity: weather.work
        name: Work
        type: weather-forecast
      - type: 'custom:dark-sky-weather-card'
        entity_current_conditions: sensor.dark_sky_icon
        entity_temperature: sensor.dark_sky_temperature
        entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1d
        entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2d
        entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3d
        entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4d
        entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5d
        entity_forecast_icon_1: sensor.dark_sky_icon_1d
        entity_forecast_icon_2: sensor.dark_sky_icon_2d
        entity_forecast_icon_3: sensor.dark_sky_icon_3d
        entity_forecast_icon_4: sensor.dark_sky_icon_4d
        entity_forecast_icon_5: sensor.dark_sky_icon_5d
        entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_0d
        entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1d
        entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2d
        entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3d
        entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4d
        entity_summary_1: sensor.dark_sky_summary_1d
        entity_summary_2: sensor.dark_sky_summary_2d
        entity_summary_3: sensor.dark_sky_summary_3d
        entity_summary_4: sensor.dark_sky_summary_4d
        entity_summary_5: sensor.dark_sky_summary_5d
    panel: false
    path: default_view
    title: General
  - badges: []
    cards:
      - aspect_ratio: 90%
        type: iframe
        url: >-
          https://embed.windy.com/embed2.html?lat=37.899953&lon=-122.052297&zoom=9&level=surface&overlay=rain&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=37.899953&detailLon=122.052297&metricWind=default&metricTemp=default&radarRange=-1
      - type: horizontal-stack
    panel: false
    theme: default
    title: Weather

```
