### ISSUE TITLE
Custom element doesn't exist: 'custom:dark-sky-weather-card'

### ISSUE THREAD

**Issue by stefancvetkovic** [iammexx/home-assistant-config#27]
I've read  [this](https://github.com/iammexx/home-assistant-config/issues/5)

But I still have hard times to make it work.
 any hints?
my ui-lovelace.yaml looks like:
```
title: My Awesome Home
resources:
  - url: /local/custom_ui/dark-sky-weather-card.js?v=7.1
  #- url:  https://unpkg.com/@polymer/lit-element@^0.5.2/lit-element.js?module
  type: module
views:
  - title: main
    icon: mdi:home-outline
    cards:
      - type: 'custom:dark-sky-weather-card'
        title: Test
       
```
